# Problem 12
# The sequence of triangle numbers is generated by adding the natural numbers.
# So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
# The first ten terms would be:
# 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
# What is the value of the first triangle number to have over five
# hundred divisors?

start_time <- Sys.time()


triangle <- function(){
  divisors <- 0
  num <- 0
  total <- 0
  while (divisors < 500){
    num <- num + 1
    total <- total + num
    divisors <- 0
    for (i in (1:(floor(total^0.5)+1))){
      if (total %% i == 0){
        if (total / i == i){
          divisors <- divisors + 1
        } else {
          divisors <- divisors + 2
        }
      }
    }
  }
  return (list(total, divisors))
}


return_vals <- triangle()

print(paste("Problem 12 =", return_vals[1], " number of divisors =", return_vals[2]))  # 76576500

end_time <- Sys.time()
print(end_time - start_time)
