import time

start_time = time.time()

# Problem 12
# The sequence of triangle numbers is generated by adding the natural numbers.
# So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
# The first ten terms would be:
# 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
# What is the value of the first triangle number to have over five
# hundred divisors?


divisors = 0
num = 0
total = 0

while divisors < 500:
    num += 1
    total += num
    divisors = 0
    for i in range(1, int(total ** 0.5) + 1):
        if total % i == 0:
            if total / i == i:
                divisors += 1
            else:
                divisors += 2

print('Problem 12 =', total, 'number of divisors', divisors)  # 76576500

print("Program took %s seconds to run." % (time.time() - start_time))
